from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config


# SELECT MODE (PRODUCTION | DEVELOPMENT)
MODE = "DEVELOPMENT"

# CLOSE ALL OPEN POSITIONS AND ORDERS
ABORT_ALL_POSITIONS = True

# FIND COINTEGRATED PAIRS
FIND_COINTEGRATED = True

# MANAGE EXITS
MANAGE_EXITS = True

# PLACE TRADES
PLACE_TRADES = True

# RESOLUTION (1MIN, 5MINS, 15MINS, 30MINS, 1HOUR, 4HOURS, 1DAY)
RESOLUTION = "1HOUR"

# STATS WINDOW
WINDOW = 21

# THRESHOLDS - OPENING
MAX_HALF_LIFE = 24
ZSCORE_THRESHOLD = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1800

# THRESHOLDS - CLOSING
CLOSE_AT_ZSCORE_CROSS = True

# ETHEREUM ADDRESS
ETHEREUM_ADDRESS = "0x79684fc8507a2D6ac57DCE3705ad6591F23CCBc0"

# WALLET PRIVATE KEY
ETH_PRIVATE_KEY = config("ETH_PRIVATE_KEY")

# KEYS - PRODUCTION
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - EXPORT
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - EXPORT
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/t9HJj_AW-ddMaDMs-5cquPhXH3f8ASeA"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/2CwgH4G0f_Og_Wu_rnn-m6UCbotQvT41"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET